### ISSUE TITLE
Add all available 6.X traits to 'Traits' seeder

### ISSUE THREAD

**Issue by Binboukami** [Binboukami/shatotto-api#13]
## Object
Add all avaialbe 'traits' to 'Traits' seeder

## Requirements

- [ ] Requires resolving issue #16 in order to implement the properties

## Todo 

- [ ] Aspect Mastery
- [ ] Maim and Mend
- [ ] Aspect Mastery II
- [ ] Thundercloud
- [ ] Aspect Mastery III
- [ ] Main and Mend II
- [ ] Firestarter
- [ ] Thunder Mastery
- [ ] Enochian
- [ ] Enhanced Freeze
- [ ] Thunder Mastery II
- [ ] Enchanced Enochian
- [ ] Enhanced Sharpcast
- [ ] Enhanced Enochian II
- [ ] Enhanced Polyglot
- [ ] Enhanced Foul
- [ ] Aspect Mastery IV
- [ ] Enhanced Manafont
- [ ] Enhanced Enochian III
- [ ] Enhanced Sharpcast II
- [ ] Aspect Mastery V

**Comment by Binboukami** [comment]
## Resolution
As commented in issue #16, 'Traits' will now be handled as controller methods and so, this issue is no longer required.
