### ISSUE TITLE
Refator 'Actions' model

### ISSUE THREAD

**Issue by Binboukami** [Binboukami/shatotto-api#18]
## Objective
Refactor 'Actions' model into a relation model with the 'Spell' Model and 'Ability' model for better scalabilty

## Requirements
- [ ] Document breaking change in the coming updates
- [ ] Define what properties are shared between 'Spells' and 'Abilities' and also which ones aren't
- [ ] Refactoring of 'Spell' and 'Ability' model

# Todo

- [ ] Document the changes that will be made in this implementation
- [ ] Create 'Spell' model
- [ ] Create 'Ability' model

**Comment by Binboukami** [comment]
## Known issue and fallback
Looked into the documentation of other FF XIV API and database.
Their solution doesn't address the separation of behavior that spells and actions have, keeping them under the same Actions entity the current state of the dev branch at a4c03a1.

This issue will be keept open until further information are collected and evalueted.
