### ISSUE TITLE
Add 'Icon' property to 'Action' model

### ISSUE THREAD

**Issue by Binboukami** [Binboukami/shatotto-api#24]
## Objective 
Add 'Icon' property to 'Action' model to enable frontend to fetch the Action icon from the backend

## Requirements
- [ ] Implementation of an image model

## Todo
- [ ] Add 'Icon' property to 'Action' model and migration
- [ ] Update all actions with the 'icon' property value

**Comment by Binboukami** [comment]
## Implementation`

The ```Icon``` property will store a **```string```** holding the url path to the icon image (png, svg or webp)
