### ISSUE TITLE
Add 'Url' property to 'Action' model

### ISSUE THREAD

**Issue by Binboukami** [Binboukami/shatotto-api#25]
## Objective 
Add 'Url' property to 'Action' model to enable users to easily fetch the action without returning a large request in the main /action route

## Requirements
- [x] Implementation of ```/action/:id``` endpoint (#30)

## Todo
- [ ] Add"Url" property to "Action' migration and seeder
- [ ] Update "Url" property in all available actions

**Comment by Binboukami** [comment]
## Implementation 
Similar to issue #24 , the ```Url``` property will accept a **```string```** value to ```/action/:id```
